### ISSUE TITLE
Feature request: Opacity control with default palette

### ISSUE THREAD

**Issue by CrystalHillVineyard** [KroneCorylus/ngx-colors#11]
It would be awesome if the opacity slider could be visible but not the color picker. The reason is that Admins choose the brand palette and Editors should only choose from default list but should have control of opacity,

**Comment by KroneCorylus** [comment]
now this is possible in version 2.8.0 setting the colorPickerControls property with the value 'only-alpha'
![Screenshot from 2021-09-23 11-02-34](https://user-images.githubusercontent.com/26716702/134521514-8b5ef0d3-b0fe-4f41-991b-1ca80ee2c44e.png)
give it a try and let me know your thoughts please.
