### ISSUE TITLE
Feature request: Ability to hide Alpha channel slider

### ISSUE THREAD

**Issue by Neon4eg** [KroneCorylus/ngx-colors#22]
It would be nice to have such option to hide Alpha slider

**Comment by KroneCorylus** [comment]
now this is possible in version 2.8.0 setting the colorPickerControls property with the value 'no-alpha'
![Screenshot from 2021-09-23 11-06-41](https://user-images.githubusercontent.com/26716702/134522242-95458028-7897-43a4-987e-ef4b00b56143.png)
