### ISSUE TITLE
Feature request: Show custom piched color in the palette

### ISSUE THREAD

**Issue by Neon4eg** [KroneCorylus/ngx-colors#23]
So I picking my custom color from picker and after that when I open the palette again I'm not able to see that color. It's hidden under PLUS button, but this in not obvious for new user.

**Comment by KroneCorylus** [comment]
I'm not sure I have understood your request.
But in version 2.8.0 the custom color selected in the color picker is shown with a little badge over the 'more colors' button, I hope this helps make it less hidden
![Screenshot from 2021-09-23 10-53-46](https://user-images.githubusercontent.com/26716702/134519915-59824ead-5860-4180-8864-9ea63bb7c909.png)
