### ISSUE TITLE
Feature request: Popup position

### ISSUE THREAD

**Issue by ServerSports** [KroneCorylus/ngx-colors#24]
It would be interesting to be able to define the position of the popup. Currently it is always under the button. Having a property like: left, right, bottom, top would greatly improve the behavior and display.

**Comment by KroneCorylus** [comment]
now in 2.9.0 you can use the new 'position' property with "bottom" or "top" values
![Screenshot from 2021-09-23 12-23-09](https://user-images.githubusercontent.com/26716702/134536230-c9c1b294-b719-476a-9228-e383740ebdbf.png)
.
