### ISSUE TITLE
color picker is not bounded to the screen

### ISSUE THREAD

**Issue by separse** [KroneCorylus/ngx-colors#26]
![image](https://user-images.githubusercontent.com/60772175/134764648-322e6798-7996-4529-be39-048912411b7a.png)
I don't want this color picker pops up out of the screen

**Comment by KroneCorylus** [comment]
Try with position="top" property

**Comment by separse** [comment]
I wanna automatically change the position to top when the popup passes the bottom of the screen.

**Comment by KroneCorylus** [comment]
done
