### ISSUE TITLE
old peerDependencies

### ISSUE THREAD

**Issue by Aeckh** [KroneCorylus/ngx-colors#27]
Have to run --legacy-peer-deps when installing if you're running newer version of angular.

Might want to use >=10.0.4 instead?  

![image](https://user-images.githubusercontent.com/8747614/140494780-6b2ae01a-aee8-43aa-ae3a-b9d1e8b0329d.png)

**Comment by KroneCorylus** [comment]
done

**Comment by Aeckh** [comment]
You can't use => 
>= should work
