### ISSUE TITLE
Error after npm install

### ISSUE THREAD

**Issue by pedig** [KroneCorylus/ngx-colors#29]
Hi,
While I am installing a package that depends on ngx-colors I got the following error:
npm ERR! Invalid tag name "=>10.0.4": Tags may not have any characters that encodeURIComponent encodes.

When I looed at https://registry.npmjs.org/ngx-colors, I see:
"peerDependencies":{"@angular/common":"~10.0.4","@angular/core":"~10.0.4","@angular/animations":"^10.0.4","@angular/forms":"~10.0.4"}
for older versions, but
{"@angular/common":"=>10.0.4","@angular/core":"=>10.0.4","@angular/animations":"=>10.0.4","@angular/forms":"=>10.0.4"}
for the latest.

Is that => syntax ok?

**Comment by KroneCorylus** [comment]
nop, is not okay, my bad.... fixed now

**Comment by KroneCorylus** [comment]
can you try installing it again ?

**Comment by pedig** [comment]
Works, thanks
