### ISSUE TITLE
Cannot set the color using a reactive form?

### ISSUE THREAD

**Issue by charlesr1971** [KroneCorylus/ngx-colors#31]
Cannot set the color when using a _reactive_ form. In _ngModel_ one can implement two way binding using:

`[(ngModel)]=“color”`

But there is no such input for _reactive_ forms?

_ngModel_ should not be mixed with _reactive_ forms, so using this methodology would be deemed as bad practice by the current **Angular** API. 

I see there is a public method called:

`setColor()`

Are we able to access this from the component that controls the template, with the embedded **ngx-colors** directive?

**Comment by KroneCorylus** [comment]
I'm not sure I understand your problem.
if you want to set the color using reactive forms you must simply set it in the formControl with pathValue()
`.patchValue('#000000')`
or during initialization
`new FormControl('#455a64');`

**Comment by charlesr1971** [comment]
OK. Thanks. This does work. 🙏
I just couldn’t see this solution in the documentation?
All the examples use the _ngModel_ methodology. Angular now recommend that _reactive_ forms should be used, going forward. 

But, thank you once again for your help.

**Comment by KroneCorylus** [comment]
You're welcome, I hope you like it and use the component.
it's not in the ngx-colors docs because it's the standard way to do it with reactive forms ([angular docs](https://angular.io/guide/reactive-forms#updating-parts-of-the-data-model)) I should probably add it anyway

**Comment by charlesr1971** [comment]
Yes. This is a truly great component.
It focuses on one thing and does that job very well. 
The animation is subtle but very stylish. 
Plus it just works out of the box. 
So many libraries nowadays, require either a lot of config or just don’t work. 
Keep up the good work. 🙏
