### ISSUE TITLE
Feature request: Anchor Element

### ISSUE THREAD

**Issue by AlbertoAcca** [KroneCorylus/ngx-colors#32]
Hi, is possible to have a feature that allow users to choose after which element the picker must be added?

now we have by  default **document.body.appendChild(this.overlay);** 

will be nice if I can tell the picker where to append. This will be a nice feature for who use Angular app as web-component

**Comment by KroneCorylus** [comment]
I do not understand, can u explain more about it ?

**Comment by AlbertoAcca** [comment]
By default the color-picker is always appended to document body.
This can cause some issues when you use the picker as web-component and wont to isolate it by using shadow DOM
If I have the possibility to choice where the picker will be appended I can isolate it and exclude all the issues. 

I hope I was clear :)

**Comment by AlbertoAcca** [comment]
...
