### ISSUE TITLE
Additional Event: colorSelect, only emitted when Select Button is clicked.

### ISSUE THREAD

**Issue by dkipping** [KroneCorylus/ngx-colors#38]
First of all: Very nice and sleek colorpicker component!

One thing that would make it more easily adaptable to more use cases would be, to not only offer the event colorChange whenever the sliders change, but additionally offer an event "colorSelect" that is only emitted on the final color selection when clicking the "Select" button.

This way, using the color and setting it only after confirmed selection would be more easily possible, allowing to cancel color change and to avoid unnecessary reactions.

Right now, there is no way to cancel the color selection in the user flow, plus expensive reactions will have to be rendered on every slider movement in real-time.

**Comment by KroneCorylus** [comment]
Hi @dkipping
thanks for the compliments.
By
> clicking the "Select" button

You meant the Accept button on the color picker section ?
![image](https://user-images.githubusercontent.com/26716702/151890363-15e0c691-9dd3-4e8c-8907-b65206d88550.png)

After reading #39 I think what it should actually do is not emit the event colorChange whenever the sliders change, bc it should not change the real value until accept button is clicked, and maybe add a new event for sliderChanges.

**Comment by dkipping** [comment]
Exactly this „Accept“ button is what I meant.

I agree, having two different events for editing the color and for a final colorChange makes sense. 

The sliderChange would have to be triggered by the alpha slider, hue slider and the color picker target point.
But what happens at user input in the text control? 

I saw in your documentation that you currently have colorChange and colorInput, but both are emitted for me when I adapt the sliders. Is colorInput supposed to only be emitted on textual input?

this would result in having 3 final events:
- colorInput
- sliderChange 
- colorChange

However changing textual input or sliders will affect the respective other controls.
This should not lead to always triggering colorInput + sliderChange, but only one of them. Otherwise, they should be merged to one common event „colorEdit“ or similar.

I hope my written thoughts are not too confusing

**Comment by KroneCorylus** [comment]
> I hope my written thoughts are not too confusing

don't worry, they're not, and i love being able to discuss these things with someone, heh

**ColorChange** event triggers whenever the color changes, even when is changed outside of the component.
**ColorInput** triggers when the color changes using the component,
**SliderChange** will trigger as you said.

I probably have to update the documentation to make it clearer
