### ISSUE TITLE
Feature Request: Cancel Button

### ISSUE THREAD

**Issue by dkipping** [KroneCorylus/ngx-colors#39]
As the name says, it would be great to not only have an "Accept" Button, but also a "Cancel" button in the color picker.

**Comment by dkipping** [comment]
Exactly, just reverting to the previous color before touching any of the sliders and color picker would make sense.

I can think of three triggers that should (from my perspective) trigger a „cancellation“:
1. clicking the back arrow 
2. Clicking a specific cancel button ( maybe cancel and accept only show after a slider/color picker/text input have been changed)
3. Just clicking outside of the complete color picker component without clicking accept

What do you think?

**Comment by KroneCorylus** [comment]
I really dont like how this looks
![image](https://user-images.githubusercontent.com/26716702/151891322-e461bf08-dd67-4381-b2c1-e0dd7832b2c6.png)
looks too clogged.
So im going to implement 1 and 3.

**Comment by dkipping** [comment]
Matter of taste. Obvious controls are good for accessibility. I‘d say one could leave it with a parameter.
But your project your choice, having any cancellation is already great. :)
