### ISSUE TITLE
Error on usage

### ISSUE THREAD

**Issue by Cafnio** [KroneCorylus/ngx-colors#41]
Hi there.

I've just started trying to use your package and I'm having some issues with it.

I have the following code:

```
selectedColor: string = '#c32af3';

<div ngx-colors-trigger style="width: 50px;height: 50px;margin:10px" [style.background]="selectedColor"
    [(ngModel)]="selectedColor">
</div>
```

and as soon as I get to that page, it returns me the following error:

```
core.js:6479 ERROR TypeError: Cannot read properties of null (reading 'writeValue')
    at setUpControl (forms.js:1574:23)
    at NgModel._setUpStandalone (forms.js:4570:9)
    at NgModel._setUpControl (forms.js:4558:37)
    at NgModel.ngOnChanges (forms.js:4518:18)
    at NgModel.rememberChangeHistoryAndInvokeOnChangesHook (core.js:1498:14)
    at callHook (core.js:2536:18)
    at callHooks (core.js:2495:17)
    at executeInitAndCheckHooks (core.js:2446:9)
    at refreshView (core.js:9480:21)
    at refreshEmbeddedViews (core.js:10590:17)
```

I am using angular version 12.2.0

Thanks for your work

**Comment by KroneCorylus** [comment]
Hi,
I can't replicate your error.
are you using the last version of the package ?
did you import NgxColorsModule in your module ?
if you use ngx-colors trigger 
`<ngx-colors ngx-colors-trigger [(ngModel)]="selectedColor"></ngx-colors>`
do you get the same error ?

**Comment by Cafnio** [comment]
> Hi, I can't replicate your error. are you using the last version of the package ? did you import NgxColorsModule in your module ? if you use ngx-colors trigger `<ngx-colors ngx-colors-trigger [(ngModel)]="selectedColor"></ngx-colors>` do you get the same error ?

Hi!

Yes, I'm using  "ngx-colors": "^2.10.2",

Imported NgxColorsModule in app.module.ts

And yes, it does the same error.

Tried to set the <ngx-color> tag on a MatModal and it shows a different error:

```
core.js:6479 ERROR TypeError: Cannot read properties of null (reading '_rawValidators')
    at getControlValidators (forms.js:882:20)
    at setUpValidators (forms.js:1646:24)
    at setUpControl (forms.js:1573:5)
    at FormGroupDirective.addControl (forms.js:5356:9)
    at NgModel._setUpControl (forms.js:4558:77)
    at NgModel.ngOnChanges (forms.js:4518:18)
    at NgModel.rememberChangeHistoryAndInvokeOnChangesHook (core.js:1498:14)
    at callHook (core.js:2536:18)
    at callHooks (core.js:2495:17)
    at executeInitAndCheckHooks (core.js:2446:9)
```

Might be something related with the code I have. But it's strange

**Comment by Cafnio** [comment]
I was able to get it working without any errors outside a form (had to import NgxColorsModule to other modules).

Looking for a way now to add it inside forms (will update this comment as soon as I get it working)

**Comment by Cafnio** [comment]
Ok was able to fix It. I was using:

```
<mat-form-field class="full-width">
       <mat-label>{{"FORM.COLOR" | translate }}</mat-label>
       <ngx-colors ngx-colors-trigger style="display: inline-block; margin:5px;" formControlName="variation">
       </ngx-colors>
</mat-form-field>
```

Using the following code, It worked properly.
   ```
<div class="full-width">
    <mat-label>{{"FORM.COLOR" | translate }}</mat-label>
   <ngx-colors ngx-colors-trigger style="display: inline-block; margin:5px;"formControlName="variation">
   </ngx-colors>
</div>
```

I leave the suggestion for allowing it to be used inside mat-form-field.

Thanks for your work! :)

**Comment by KroneCorylus** [comment]
Can be used inside a form, but you shouldn't use ngModel, inside a form you should use formControlName
[angular docs](https://angular.io/api/forms)
