### ISSUE TITLE
Make this library compatible with the Angular 13 format

### ISSUE THREAD

**Issue by jogelin** [KroneCorylus/ngx-colors#47]
Since Angular 13, the libraries should follow a specific format to be compatible:

https://angular.io/guide/angular-package-format

**Comment by KroneCorylus** [comment]
I really don't know what I have to do to comply with this,
When I have more time I will continue investigating, be patient with me for now

**Comment by kfrederix** [comment]
@jogelin  @KroneCorylus 
I opened this PR with upgrade to Angular 13. I believe it fixes the APF as well:
https://github.com/KroneCorylus/ngx-colors/pull/56
