### ISSUE TITLE
How to change height ?

### ISSUE THREAD

**Issue by boskiv** [KroneCorylus/ngx-colors#48]
![Screen Shot 2022-02-14 at 20 20 43](https://user-images.githubusercontent.com/1939783/153980294-73d5b0cf-c786-4c9e-8669-9cad424dfa2f.png)
I've tried a few ways but inline style has higher priority right ?
Can I make a button 10px ?

I guess somehow I can redefine $size from ngx-colors.component.scss ? 
Can you point me right way to do that >

**Comment by donbwhite** [comment]
You'll need to add ::ng-deep like this
`::ng-deep .app-color-picker {
  & .preview {
    height: 40px;
    width: 40px;
    & .preview-background {
      height: 34px;
      width: 34px;
    }
    & .circle {
      height: 34px !important;
      width: 34px !important;
    }
  }
}`

**Comment by KroneCorylus** [comment]
HI @boskiv, 
I don't think im going to implement a way that allows users to modify the size and styles of the various elements of the component. I recommend you try @donbwhite  solution or download the source code edit the scss files and use your modified version.
Sorry I can't be of more help.

**Comment by KroneCorylus** [comment]
> I don't think im going to implement a way that allows users to modify the size and styles of the various elements of the component.
at least not for now.
