### ISSUE TITLE
Data URI and content security policy

### ISSUE THREAD

**Issue by Yanal-Yves** [KroneCorylus/ngx-colors#52]
Hello,

Thank you for sharing this code.

This library uses data URI which are considered unsafe :
- [MDM states it's insecure](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/Sources#scheme-source)
- [This stack exchange also states it's insecure and says there is no way to allow only some of them](https://security.stackexchange.com/questions/94993/is-including-the-data-scheme-in-your-content-security-policy-safe)

I would be happy to contribute but I am not sure how an Angular library should handled images in theirs components.

Thus I have copy/paste the source code of this library components in my app source code and changed the data URI to HTTPS URI.

What's the best practice to handle images in a library without compromising security ?

**Comment by KroneCorylus** [comment]
Hi, @Yanal-Yves.
I think there is no way to include non-base64 images without forcing the user to include them in the angular.json file or some other configuration file.
I could try to remove the images and replace them with css gradients, I'll look into it, thanks for the warning

**Comment by Yanal-Yves** [comment]
Hi,

In ngx-colors/projects/ngx-colors/src/lib/components/color-picker/color-picker.component.scss, in `.color-picker .hue`, you can replace the background-image with 

``` css
background: linear-gradient(to right, red 0%, #ff0 17%, lime 33%, cyan 50%, blue 66%, #f0f 83%, red 100%);
```

The result of this change can be seen/tested here : https://ngx-color-examples-404ft6zmi-yanalyvesfargialla.vercel.app/

Any advice for the other images ?

**Comment by Yanal-Yves** [comment]
OK maybe with something like 

``` css
background: linear-gradient(to right, rgb(125, 61, 61) 0%, rgba(125, 61, 61, 0) 100%);
```
I'll try that later when I have time

**Comment by KroneCorylus** [comment]
great! 
for saturation-lightness div: 
```
  background-image:
    linear-gradient(to top, #000 0%, transparent 100%),   /* lightness*/
    linear-gradient(to right, #fff 0%, transparent 100%); /* saturation */
```
alpha already uses gradient
and the one you provide for hue seems to works just fine, is a little off compared to the image, but i dont think it matters
![image](https://user-images.githubusercontent.com/26716702/158032660-58d1c3c5-1511-4f93-96cd-bb63592d0970.png)

**Comment by KroneCorylus** [comment]
Thanks for the contribution!

**Comment by KroneCorylus** [comment]
alpha grid
  background-image: linear-gradient(45deg, #ccc 25%, transparent 25%),linear-gradient(-45deg, #ccc 25%, transparent 25%),linear-gradient(45deg, transparent 75%, #ccc 75%),linear-gradient(-45deg, transparent 75%, #ccc 75%);
  background-size: 16px 16px;
  background-position: 0 0, 0 8px, 8px -8px, -8px 0px;

**Comment by KroneCorylus** [comment]
all data:image/png;base64 are removed on 3.0.4
