### ISSUE TITLE
Bug with validation

### ISSUE THREAD

**Issue by yklepikovska-iqmessenger** [KroneCorylus/ngx-colors#54]
If type incorrect color to input 
![image](https://user-images.githubusercontent.com/85672607/159885829-1d934363-4500-4251-bd84-7108eaa30daa.png)
user can not open colorpicker anymore and we see errors in console 
![image](https://user-images.githubusercontent.com/85672607/159886143-25779dd3-0368-4e1c-8a16-1338b06575bc.png)

**Comment by KroneCorylus** [comment]
Hi, Thanks 
supposedly fixed in 3.0.5

**Comment by yklepikovska-iqmessenger** [comment]
Looks like it works fine in 3.0.5. Thank you!
