### ISSUE TITLE
Empty color selection

### ISSUE THREAD

**Issue by ricavir11** [KroneCorylus/ngx-colors#57]
Is it possible to reset color value to undefined ?
I've tried to add an "undefined" item to colorPalette array but I'm getting an error :

`TypeError: Cannot read properties of undefined (reading 'variants')`

Do you have a workarround to suggest ? 
If not, is it possible to add this possibility ?

**Comment by KroneCorylus** [comment]
maybe a transparent color like 'rgba(0,0,0,0)' is good for you, but if you need the value 'undefined'  there is no way right now.
but i will work on it

**Comment by vacants** [comment]
Definitely need this :P

**Comment by KroneCorylus** [comment]
Done in 3.1.3
