### ISSUE TITLE
Missing UI logic

### ISSUE THREAD

**Issue by genemars** [KroneCorylus/ngx-colors#6]
Hi, this is a very neat control for color selection but it seems lacking some UI logic:

- when adding a color, it seems that there is no way of detecting when the user presses the back or accept button
- when adding a color, shouldn't the back button restore the current color to the previous value?
- how to remove a color from the palette?
- I don't see any difference between the `(change)` and `(input)` events

Thanks =)

**Comment by KroneCorylus** [comment]
Hi! thanks for the feedback.

> * when adding a color, it seems that there is no way of detecting when the user presses the back or accept button
> * when adding a color, shouldn't the back button restore the current color to the previous value?

"+" is more like "more colors" than "adding a color" but it is true that perhaps the correct behavior when touching "<-" would be to leave the color that was selected before touching the sliders.I will fix it for the next version thanks.

> * how to remove a color from the palette?

not currently possible. It is not intended for the user to customize the palette on the fly. but i can think about it
> * I don't see any difference between the `(change)` and `(input)` events

(input) should only fire when the value is changed using the component 
while (change) should be fired even when the value is changed outside the component. if this is not working as intended let me know.
