### ISSUE TITLE
Use custom z-index for the picker panel

### ISSUE THREAD

**Issue by sha-N** [KroneCorylus/ngx-colors#61]
I really like the UI of this library as compared to the one I'm currently using, great job. But have an issue with `z-index`

Now the `z-index` value for the picker panel is coming from the constant `OVERLAY_STYLES`, is it possible to update this value. 

In my case I have a value higher than 2000 for my cdk-overlay class.

**Comment by KroneCorylus** [comment]
Yes, you can use the overlayClassName property in the ngx-colors-trigger directive
``` 
<ngx-colors ngx-colors-trigger overlayClassName="myClass"></ngx-colors>
```
make sure to put this class on the root styles of your proyect and probably you will need to add the !important property to override the default z-index
