### ISSUE TITLE
[BUG] Editing hex value on 2nd input screen and clicking 'ACCEPT' results in color defaulting to #FF0000

### ISSUE THREAD

**Issue by brx-tyler** [KroneCorylus/ngx-colors#63]
When editing the hex value on the 2nd screen, the value always reverts to #FF0000 when 'ACCEPT' is clicked. Hitting enter or clicking outside the modal causes the color to be accepted correctly. Choosing a color with the color picker and clicking 'ACCEPT' causes the color to be accepted correctly. 

**STEPS TO REPRODUCE:**

- Click on color circle to open color picker
- Click on down arrow to open 2nd screen
- Edit hex value
- Click 'ACCEPT'
- Observe that the color is saved as #FF0000

1
<img width="296" alt="Screen Shot 2022-06-21 at 11 06 01 AM" src="https://user-images.githubusercontent.com/104032993/174833691-80148adc-6872-4788-a12a-cda90ae5280c.png">
2
<img width="249" alt="Screen Shot 2022-06-21 at 11 06 10 AM" src="https://user-images.githubusercontent.com/104032993/174833692-6fa5d5dd-08bd-4544-9fe4-7d8d0a051a6a.png">
3
<img width="251" alt="Screen Shot 2022-06-21 at 11 06 25 AM" src="https://user-images.githubusercontent.com/104032993/174833694-3ebc54ee-3edd-467d-bdca-a81befcc2b43.png">
4
<img width="189" alt="Screen Shot 2022-06-21 at 11 06 33 AM" src="https://user-images.githubusercontent.com/104032993/174833695-84d60cf8-d905-4948-9109-104b3f0e2c69.png">

**Comment by hebaelliethy** [comment]
Any plans to get this fixed?

**Comment by KroneCorylus** [comment]
Fix on 3.1.3
