### ISSUE TITLE
public sliderChange event

### ISSUE THREAD

**Issue by AndrusGerman** [KroneCorylus/ngx-colors#66]
Problem: I am creating an application, where I would like to see the colors I am testing in 'color-picker', outside of its component.
The problem is the following, apparently there is no way to access the 'sliderChange' events.

My proposal is to add an 'Output sliderChange', to be able to live the colors in real time, and a second ouput if this color was confirmed.

The current features would be kept, but for people who want more control over what colors the user is previewing this would be a great feature.

The reason why this is useful to me: 

I find this feature useful as I am building an application that modifies its own colors. And I want to see the changes in real time of what it would look like, without having to save, open again and try, all the time, it's very cumbersome

**Comment by KroneCorylus** [comment]
you can do this with the slider event
`(slider)="console.log($event)"`
