### ISSUE TITLE
Site down, all examples using ngModel instead of reactiveForms, error integrating in a reactive form

### ISSUE THREAD

**Issue by Sharlaan** [KroneCorylus/ngx-colors#76]
Hello pretty lib compatible with Angular15

... but i'm having troubles integrating it in my reactive form: (AngularMaterial15)

```ts
<form [formGroup]="appForm" (ngSubmit)="onSubmit()">
  ...
  <mat-form-field>
    <mat-label>Icon background color</mat-label>
    <input matInput ngx-colors-trigger formControlName="iconBgColor" />
  </mat-form-field>
  ...
  <mat-form-field>
    <mat-label>Icon background color</mat-label>
    <input matInput readOnly [value]="appForm.get('iconBgColor')?.value" />
    <ngx-colors matSuffix ngx-colors-trigger formControlName="iconBgColor"></ngx-colors>
  </mat-form-field>
  ...
</form>
```

```ts
appForm = this.fb.group<FormType<HomeApp, 'uuid'>>(
    {
      ...
      iconBgColor: this.fb.control('#FFFFFF'), // default #FFFFFF (white),
      ...
    },
    {
      updateOn: 'blur',
    },
  );
```

First integration errors on selecting a color with :
![image](https://user-images.githubusercontent.com/2692027/215504396-75d6da3b-fc8e-4141-89c9-fe1f58113ff4.png)

Second one does not error at all, but does not update the value o.O

I tried to find examples but site is down, and code examples seem to all be based on ngModel ...

What am i missing ?

**Comment by Sharlaan** [comment]
UPDATE:
Second integration works but i had to change the field update mode:
`iconBgColor: this.fb.control('#FFFFFF', { updateOn: 'change' }), // default #FFFFFF (white)`

i prefer the first integration but it does not work....

**Comment by KroneCorylus** [comment]
Site Up, thanks for the headup.
Checking the updateOn: 'blur' option now.

**Comment by Sharlaan** [comment]
Hello nice reactivity thanks ! +1

I finally made it work with this implementation :
![image](https://user-images.githubusercontent.com/2692027/215519190-4d3c4e64-7005-4a31-b80c-2485e25262d0.png)
```ts
  <div>
    <label for="color-picker">Icon Background Color</label>
    <ngx-colors
      id="color-picker"
      ngx-colors-trigger
      formControlName="iconBgColor"
      [title]="appForm.get('iconBgColor')?.value"
    ></ngx-colors>
  </div>
```
```ts
appForm = this.fb.group<FormType<HomeApp, 'uuid'>>(
    {
      ...
      iconBgColor: this.fb.control('#FFFFFF', { updateOn: 'change' }), // default #FFFFFF (white),
      ...
    },
    {
      updateOn: 'blur',
    },
  );
```

**Comment by KroneCorylus** [comment]
Added support for updateOn:'blur', Version 3.3.0. Please update and let me know if you have any problem
