### ISSUE TITLE
Add possibility to pass by @Input() buttons names in color picker instead of 'Accept' and 'Cancel' by deafault 

### ISSUE THREAD

**Issue by michalgrzegorczyk-dev** [KroneCorylus/ngx-colors#78]

**Comment by KroneCorylus** [comment]
Hi, This is already possible through the cancelLabel and acceptLabel attributes. Is on the docs, you can also find examples of this on the examples page on the website.

**Comment by michalgrzegorczyk-dev** [comment]
Hi, thanks. Didn't catch that ;)
