### ISSUE TITLE
Trigger on popup closed

### ISSUE THREAD

**Issue by michalgrzegorczyk-dev** [KroneCorylus/ngx-colors#79]
Is it possible to implement trigger when popup with choosen color is closed? I'm trying to implement group of colors with add color button but only what I can see is (input) or (change) so if I change i.e. hex it adds colors when I'm typing.

**Comment by KroneCorylus** [comment]
yes, i could add a onClose, onOpen Event, thats sound like a good idea.

**Comment by michalgrzegorczyk-dev** [comment]
Nice :) When I can expect that change?

**Comment by michalgrzegorczyk-dev** [comment]
Hey @KroneCorylus, could you give an approximate time?

**Comment by KroneCorylus** [comment]
Added on 3.5.0
