### ISSUE TITLE
Error: Providers from the `BrowserModule` have already been loaded.

### ISSUE THREAD

**Issue by voria** [KroneCorylus/ngx-colors#82]
I've updated ngx-colors in my project to latest version 3.5.1 and now an error is thrown because of `BrowserAnimationsModule` being imported multiple times.

This is the error:

``Error: Providers from the `BrowserModule` have already been loaded. If you need access to common directives such as NgIf and NgFor, import the `CommonModule` instead.``

Since the module can be imported only once, I think a library should avoid to force-import it, instead it should be imported by the application.

Reverting commit f4682b6 fixes the issue.

**Comment by KroneCorylus** [comment]
fixed on 3.5.2
