### ISSUE TITLE
Active color displays incorrectly when the first color in presets is selected

### ISSUE THREAD

**Issue by aliaksandrviarshel** [KroneCorylus/ngx-colors#86]
Relevant for version of the package 3.5.2.
The bug can be reproduced in the examples of the package [here](https://ngx-colors.web.app/).
### Description
When the first color from presets is selected, active color also displays on the palette button.
![image](https://user-images.githubusercontent.com/88730353/236477795-846d5f0a-0acc-4b5b-99e9-f1a0c784fed0.png)
But when I select any other color from presets except the first one, active color does not display on the palette button.
![image](https://user-images.githubusercontent.com/88730353/236478060-e29eb848-716c-4d09-95b7-5a86ad2b6b24.png)
### Expected behaviour
When any color from presets (including the first one) is selected the active color does not display on the palette button.

**Comment by KroneCorylus** [comment]
fixed. Should be resolved in the next release.
