### ISSUE TITLE
Popup not bound to screen / missing position style attributes

### ISSUE THREAD

**Issue by REPTILEHAUS** [KroneCorylus/ngx-colors#92]
using the demo code, the popup is positioned in the top left with no style attributes added. NG 15 

<img width="516" alt="Screenshot 2023-07-20 at 13 05 12" src="https://github.com/KroneCorylus/ngx-colors/assets/4680621/f34a9625-b877-4be3-bb91-8a184d042f18">

**Comment by KroneCorylus** [comment]
sorry but im not able to reproduce this issue, are you using the latest version ?
