### ISSUE TITLE
open is not EventEmitter

### ISSUE THREAD

**Issue by zipporaSay** [KroneCorylus/ngx-colors#95]
as written in docs open and close is outputs events
and have to be event emitters like input
but **not!**
in library code :
    change: EventEmitter<string>;
    input: EventEmitter<string>;
    slider: EventEmitter<string>;
    onClick(): void;
    constructor(triggerRef: ElementRef, panelFactory: PanelFactoryService);
    panelRef: ComponentRef<PanelComponent>;
    isDisabled: boolean;
    onTouchedCallback: () => void;
    onChangeCallback: (_: any) => void;
    open(): void;
    close(): void;
    onChange(): void;

can you give me an example how to trigger open palette event?

**Comment by zipporaSay** [comment]
i use 3.0.5 version seems it is a new feature

**Comment by alexanderkenney** [comment]
@zipporaSay - I have to use version 12 of angular for various reasons. This restricts me to version 3.1.0 of ngx-colors. To get round the issue of the open and close events not being available, I use the ngx-colors-trigger inside a <button />. This allows me to use the (click) event. This is a reasonable proxy for the (open) event.
